In [1]:
from datasets import load_dataset

ds = load_dataset("cfilt/iitb-english-hindi")

C:\Users\Naman Rajput\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
ds

DatasetDict({
    train: Dataset({
        features: ['translation'],
        num_rows: 1659083
    })
    validation: Dataset({
        features: ['translation'],
        num_rows: 520
    })
    test: Dataset({
        features: ['translation'],
        num_rows: 2507
    })
})

In [3]:
ds['train']['translation']

[{'en': 'Give your application an accessibility workout',
  'hi': 'अपने अनुप्रयोग को पहुंचनीयता व्यायाम का लाभ दें'},
 {'en': 'Accerciser Accessibility Explorer',
  'hi': 'एक्सेर्साइसर पहुंचनीयता अन्वेषक'},
 {'en': 'The default plugin layout for the bottom panel',
  'hi': 'निचले पटल के लिए डिफोल्ट प्लग-इन खाका'},
 {'en': 'The default plugin layout for the top panel',
  'hi': 'ऊपरी पटल के लिए डिफोल्ट प्लग-इन खाका'},
 {'en': 'A list of plugins that are disabled by default',
  'hi': 'उन प्लग-इनों की सूची जिन्हें डिफोल्ट रूप से निष्क्रिय किया गया है'},
 {'en': 'Highlight duration', 'hi': 'अवधि को हाइलाइट रकें'},
 {'en': 'The duration of the highlight box when selecting accessible nodes',
  'hi': 'पहुंचनीय आसंधि (नोड) को चुनते समय हाइलाइट बक्से की अवधि'},
 {'en': 'Highlight border color',
  'hi': 'सीमांत (बोर्डर) के रंग को हाइलाइट करें'},
 {'en': 'The color and opacity of the highlight border.',
  'hi': 'हाइलाइट किए गए सीमांत का रंग और अपारदर्शिता। '},
 {'en': 'Highlight fill color', 'hi': 'भराई के रंग को हाइलाइट करें'},
 {'en': 'The color and opacity of the highlight fill.',
  'hi': 'हाइलाइट किया गया भराई का रंग और पारदर्शिता। '},
 {'en': 'API Browser', 'hi': 'एपीआई विचरक'},
 {'en': 'Browse the various methods of the current accessible',
  'hi': 'इस समय जिसे प्राप्त किया गया हो, उसकी विभिन्न विधियों (मेथड) में विचरण करें'},
 {'en': 'Hide private attributes', 'hi': 'निजी गुणों को छिपाएं'},
 {'en': 'Method', 'hi': 'विधि'},
 {'en': 'Property', 'hi': 'गुणधर्म'},
 {'en': 'Value', 'hi': 'मान'},
 {'en': 'IPython Console', 'hi': 'आईपाइथन कन्सोल'},
 {'en': 'Interactive console for manipulating currently selected accessible',
  'hi': 'इस समय चुने गए एक्सेसेबेल से काम लेने के लिए अंतर्क्रियात्मक कन्सोल'},
 {'en': 'Event monitor', 'hi': 'घटना मानिटर'},
 {'en': '_ Monitor Events', 'hi': 'घटनाओं को मानिटर करें (_ M) '},
 {'en': 'C _ lear Selection', 'hi': 'चुनाव को हटाएं (C _) '},
 {'en': 'Everything', 'hi': 'सभी'},
 {'en': 'Selected application', 'hi': 'चुने गए अनुप्रयोग'},
 {'en': 'Selected accessible', 'hi': 'चुने गए एक्सेसेबेल'},
 {'en': 'Source', 'hi': 'स्रोत'},
 {'en': 'Event Monitor', 'hi': 'घटना मानिटर'},
 {'en': 'Shows events as they occur from selected types and sources',
  'hi': 'चुने गए प्रकारों और स्रोतों से घटनाएं जैसे-जैसे घटित होती हैं, उन्हें दर्शाता है'},
 {'en': 'Highlight last event entry',
  'hi': 'अंतिम प्रविष्ट घटना को हाइलाइट करो'},
 {'en': 'Start / stop event recording', 'hi': 'घटना रेकोर्डिंग शुरू करो/रोको'},
 {'en': 'Clear event log', 'hi': 'घटना रोजनामचा मिटाओ'},
 {'en': '(no description)', 'hi': 'कोई विवरण नहीं'},
 {'en': 'Description', 'hi': 'वर्णन'},
 {'en': 'Show', 'hi': 'दिखाएं'},
 {'en': '_ Accessible', 'hi': 'पहुंचनीय'},
 {'en': 'Perform action', 'hi': 'कार्रवाई संपन्न करें'},
 {'en': 'Acti _ on', 'hi': 'कार्रवाई (_ o) '},
 {'en': 'ID', 'hi': 'आईडी'},
 {'en': 'Toolkit', 'hi': 'औजार बक्सा'},
 {'en': 'Version', 'hi': 'संस्करण'},
 {'en': 'Ap _ plication', 'hi': 'अनुप्रयोग'},
 {'en': 'Col _ lection', 'hi': 'संग्रह'},
 {'en': '0, 0', 'hi': '0, 0'},
 {'en': 'Relative position', 'hi': 'सापेक्ष स्थिति'},
 {'en': 'Size', 'hi': 'आकार'},
 {'en': 'WIDGET', 'hi': 'विडजेट'},
 {'en': 'Layer', 'hi': 'स्तर'},
 {'en': 'MDI - Z - order', 'hi': 'एमडीआई-जेड-क्रम'},
 {'en': 'Alpha', 'hi': 'अल्फा'},
 {'en': 'Absolute position', 'hi': 'निरपेक्ष स्थिति'},
 {'en': 'Co _ mponent', 'hi': 'घटक'},
 {'en': 'Des _ ktop', 'hi': 'डेस्कटोप'},
 {'en': 'Locale:', 'hi': 'स्थान-विशिष्टः'},
 {'en': '_ Document', 'hi': 'प्रलेख'},
 {'en': 'Hyperlink', 'hi': 'हाइपरकड़ी'},
 {'en': 'H _ ypertext', 'hi': 'हाइपरपाठ'},
 {'en': 'Position', 'hi': 'स्थिति'},
 {'en': 'Description', 'hi': 'वर्णन'},
 {'en': 'Locale', 'hi': 'स्थान-विशिष्ट'},
 {'en': '_ Image', 'hi': 'छवि (_ I) '},
 {'en': 'Lo _ gin Helper', 'hi': 'प्रवेश सहायक'},
 {'en': 'Select All', 'hi': 'सभी चुनें'},
 {'en': '_ Selection', 'hi': 'चयन (_ S) '},
 {'en': 'St _ reamable Content', 'hi': 'प्रवाहित करनेयोग्य विषयवस्तु'},
 {'en': 'Selected columns', 'hi': 'चुने गए स्तंभ'},
 {'en': 'Selected rows', 'hi': 'चुनी गई पंक्तियां'},
 {'en': 'Columns', 'hi': 'स्तंभ'},
 {'en': 'Rows', 'hi': 'पंक्तियां'},
 {'en': 'Table Information', 'hi': '& lt; bgt; सारणी सूचनाlt;/bgt; '},
 {'en': 'name (x, y)', 'hi': 'नाम (x, y) '},
 {'en': 'Header:', 'hi': 'शीर्षकः'},
 {'en': 'Extents:', 'hi': 'विस्तारः'},
 {'en': 'Row', 'hi': 'पंक्ति'},
 {'en': 'Column', 'hi': 'स्तंभ'},
 {'en': 'Selected Cell', 'hi': '& lt; bgt; चुनी गई कोशिकाlt;/bgt; '},
 {'en': '_ Table', 'hi': 'सारणी (_ T) '},
 {'en': 'Offset', 'hi': 'ओफसेट'},
 {'en': 'Include defaults', 'hi': 'डिफोल्टों को शामिल करें'},
 {'en': 'Te _ xt', 'hi': 'पाठ (_ x) '},
 {'en': 'Current value', 'hi': 'मौजूदा मान'},
 {'en': 'Minimum increment', 'hi': 'न्यूनतम वृद्धि'},
 {'en': 'Maximum value', 'hi': 'अधिकतम मान'},
 {'en': 'Minimum value', 'hi': 'न्यूनतम मान'},
 {'en': 'Val _ ue', 'hi': 'मान'},
 {'en': 'Interface Viewer', 'hi': 'अंतराफलक दर्शक'},
 {'en': 'Allows viewing of various interface properties',
  'hi': 'अंतराफलक के विभिन्न गुणों को देखने देता है'},
 {'en': '(not implemented)', 'hi': '(क्रियान्वित नहीं हुआ है) '},
 {'en': 'Name', 'hi': 'नाम'},
 {'en': 'URI', 'hi': 'यूआरआई'},
 {'en': 'Start', 'hi': 'प्रारंभ'},
 {'en': 'End', 'hi': 'अंत'},
 {'en': 'Too many selectable children', 'hi': 'बहुत अधिक चयनीय शिशु हैं'},
 {'en': 'Quick Select', 'hi': 'तेज चुनाव'},
 {'en': 'Plugin with various methods of selecting accessibles quickly.',
  'hi': 'प्लग-इन जिसमें हैं एक्सेसेबेलों को तेजी से चुनने के लिए कई विधियां'},
 {'en': 'Inspect last focused accessible',
  'hi': 'अंतिम बार फोकस किए गए एक्सेसेबल को जांचें'},
 {'en': 'Inspect accessible under mouse',
  'hi': 'माउस के अधीन जो एक्सेसेबल है, उसे जांचें'},
 {'en': 'Native', 'hi': 'वतनी'},
 {'en': 'Dogtail', 'hi': 'श्वानपुच्छ'},
 {'en': 'LDTP', 'hi': 'एलडीटीपी'},
 {'en': 'Script Type', 'hi': 'लिपि प्रकार'},
 {'en': 'Script Recorder', 'hi': 'लिपि रेकोर्डर'},
 {'en': 'Creates dogtail style scripts',
  'hi': 'श्वानपुच्छ शैली की लिपियां निर्मित करता है'},
 {'en': 'The current script will be lost.',
  'hi': 'वर्तमान लिपि (स्क्रिप्ट) खो जाएगी। '},
 {'en': 'Confirm clear', 'hi': 'मिटाने की पुष्टि करें'},
 {'en': 'Sche _ ma:', 'hi': 'स्कीमाः'},
 {'en': 'V _ alidate', 'hi': 'सत्यापन'},
 {'en': 'Idle', 'hi': 'खाली'},
 {'en': 'No description', 'hi': 'कोई विवरण नहीं'},
 {'en': 'AT - SPI Validator', 'hi': 'एटी-एसपीआई सत्यापक'},
 {'en': 'Validates application accessibility',
  'hi': 'अनुप्रयोग की पहुंचनीयता का सत्यापन करता है'},
 {'en': 'Level', 'hi': 'स्तर'},
 {'en': 'Role', 'hi': 'भूमिका'},
 {'en': 'Saving', 'hi': 'सहेज रहे हैं'},
 {'en': 'Validating', 'hi': 'पुष्टि कर रहे हैं'},
 {'en': 'EXCEPT', 'hi': 'अपवाद'},
 {'en': 'ERROR', 'hi': 'त्रुटि'},
 {'en': 'WARN', 'hi': 'चेतावनी'},
 {'en': 'INFO', 'hi': 'सूचना'},
 {'en': 'DEBUG', 'hi': 'दोषमुक्त करें'},
 {'en': 'Basic', 'hi': 'मूल'},
 {'en': 'Tests fundamental GUI application accessibility',
  'hi': 'मूलभूत जीयूआई अनुप्रयोग पहुंचनीयता का परीक्षण करता है'},
 {'en': 'actionable% s is not focusable or selectable',
  'hi': '% s जिस पर कार्रवाई हो सकती है, वह न तो फोकस करने योग्य है न ही चयनीय'},
 {'en': 'interactive% s is not actionable',
  'hi': 'अंतर्क्रियात्मक% s कार्रवाई करने योग्य नहीं है'},
 {'en': 'more than one focused widget', 'hi': 'एक से अधिक विडजेट फोकस में है'},
 {'en': '% s has no text interface', 'hi': '% s का कोई पाठ अंतराफलक नहीं है'},
 {'en': '% s index in parent does not match child index',
  'hi': 'अभिभावक में% s सूची शिशु सूची सेमेल नहीं खाती'},
 {'en': 'Missing reciprocal for% s relation',
  'hi': '% s संबंध के लिए अन्योन्य गायब है'},
 {'en': '% s missing name or label', 'hi': '% s गायब नाम या सूचक'},
 {'en': 'focusable% s has table interface, no selection interface',
  'hi': 'फोकस योग्य% s में सारणी अंतराफलक है, कोई चयनीय अंतराफलक नहीं हैbutton has focused state without focusable state'},
 {'en': '% s has% s state without% s state',
  'hi': '% s में% s स्थिति है, पर उसके साथ% s स्थिति नहीं है'},
 {'en': '% s does not belong to a set',
  'hi': '% s किसी समुच्चय का सदस्य नहीं है'},
 {'en': '% (rolename) s index% (num) d does not match row and column',
  'hi': '% (rolename) s सूची% (num) d पंक्ति और स्तंभ से मेल नहीं खातेparent indexrow and column index'},
 {'en': '% (rolename) s parent index% (num1) d does not match row and column index% (num2) d',
  'hi': '% (rolename) s अभिभावक सूची% (num1) d पंक्ति और स्तंभ सूची% (num2) d से मेल नहीं खाते'},
 {'en': '% s has no name or description',
  'hi': '% s का कोई नाम या विवरण नहीं'},
 {'en': '_ Preferences...', 'hi': 'पसंद (_ P)... '},
 {'en': '_ Contents', 'hi': 'विषय सूची (_ C) '},
 {'en': 'Accerciser could not see the applications on your desktop. You must enable desktop accessibility to fix this problem. Do you want to enable it now?',
  'hi': 'एक्सेरसाइसर आपके डेस्कटोप में मौजूद अनुप्रयोग नहीं देख पाया। इस समस्या के समाधान के लिए आपको डेस्कटोप पहुंचनीयता को सक्रिय करना होगा। क्या आप इसे सक्रिय करना चाहते हैं? '},
 {'en': 'Note: Changes only take effect after logout.',
  'hi': 'टिप्पणीः परिवर्तन सत्रांत (लोगआउट) के बाद ही प्रभाव में आएंगे। '},
 {'en': 'Children', 'hi': 'शिशु'},
 {'en': '_ Refresh Registry', 'hi': 'पंजी ताजा करें (_ R) '},
 {'en': 'Refresh all', 'hi': 'सभी को ताजा करें'},
 {'en': 'Refresh _ Node', 'hi': 'आसंधि (नोड) को ताजा करें (_ N) '},
 {'en': "Refresh selected node 's children",
  'hi': 'चुनी गई आसंधियों (नोड) के शिशुओं को ताजा करें'},
 {'en': 'Component', 'hi': 'घटक'},
 {'en': 'Task', 'hi': 'कार्य'},
 {'en': 'Key', 'hi': 'कुंजी'},
 {'en': 'Alt', 'hi': 'आल्ट'},
 {'en': 'Ctrl', 'hi': 'कंट्रोल'},
 {'en': 'Shift', 'hi': 'शिफ्ट'},
 {'en': 'Top panel', 'hi': 'ऊपरी पटल'},
 {'en': 'Bottom panel', 'hi': 'निचला पटल'},
 {'en': 'accerciser Preferences', 'hi': 'एक्सेर्साइसर पसंद'},
 {'en': 'Plugins', 'hi': 'प्लगइन्स'},
 {'en': 'Global Hotkeys', 'hi': 'सार्वत्रिक फटाफट कुंजियां'},
 {'en': 'Highlighting', 'hi': 'हाइलाइटन'},
 {'en': 'Highlight duration:', 'hi': 'हाइलाइट अवधिः'},
 {'en': 'Border color:', 'hi': 'सीमांत रंगः'},
 {'en': 'The border color of the highlight box',
  'hi': 'हाइलाइट बक्से का सीमांत रंग'},
 {'en': 'Fill color:', 'hi': 'भराई का रंगः'},
 {'en': 'The fill color of the highlight box',
  'hi': 'हाइलाइट बक्से का भराई रंग'},
 {'en': 'translator - credits',
  'hi': 'रविशंकर श्रीवास्तव (raviratlami @yahoo. com) राजेश रंजन (rajeshkajha @yahoo. com) ल. बालसुब्रमण्यम (l. balasubramaniam @gmail. com) '},
 {'en': 'An interactive Python accessibility explorer',
  'hi': 'एक अंतर्क्रियात्मक पाइथन पहुंचनीयता अन्वेषक'},
 {'en': 'accerciser Copyright © 2006, 2007 IBM Corporation (BSD)',
  'hi': 'एक्सेर्साइसर सर्वाधिकार © 2006,2007 आईबीएम निगम (बीएसडी) '},
 {'en': 'The New BSD License See the COPYING and NOTICE files for details.',
  'hi': 'नया बीएसडी लाइसेन्स विवरण के लिए देखिए प्रतिलिपीकरण और सूचना फाइलें'},
 {'en': 'Web site', 'hi': 'जाल स्थल'},
 {'en': '_ Add Bookmark...', 'hi': 'पसंद जोड़ें... (_ A) '},
 {'en': 'Bookmark selected accessible.',
  'hi': 'चुने गए एक्सेसेबलों को पुस्तक-चिह्नित करें'},
 {'en': '_ Edit Bookmarks...', 'hi': 'पुस्तक चिह्न संपादित करें (_ E)... '},
 {'en': 'Manage bookmarks.', 'hi': 'पुस्तक-चिह्नों को प्रबंधित करें। '},
 {'en': 'Edit Bookmarks...', 'hi': 'पुस्तक चिह्नों को संपादित करें... '},
 {'en': 'Title', 'hi': 'शीर्षक'},
 {'en': 'Application', 'hi': 'अनुप्रयोग'},
 {'en': 'Path', 'hi': 'पथ'},
 {'en': 'Add Bookmark...', 'hi': 'पुस्तक-चिह्न जोड़ें... '},
 {'en': 'Title:', 'hi': 'शीर्षकः'},
 {'en': 'Application:', 'hi': 'अनुप्रयोगः'},
 {'en': 'Path:', 'hi': 'पथः'},
 {'en': 'Plugin Errors', 'hi': 'प्लग-इन त्रुटियां'},
 {'en': 'View', 'hi': 'दृश्य'},
 {'en': 'No view', 'hi': 'कोई दृश्य नहीं है'},
 {'en': '_ Single plugins view', 'hi': 'एकल प्लग-इन दृश्य'},
 {'en': 'Plugin View', 'hi': 'प्लग-इन दृश्य'},
 {'en': 'Plugin View (% d)', 'hi': 'प्लग-इन दृश्य (% d) '},
 {'en': '_ New view...', 'hi': 'नया दृश्य... '},
 {'en': 'New View...', 'hi': 'नया दृश्य... '},
 {'en': '_ File', 'hi': 'फाइल (F) '},
 {'en': '_ Edit', 'hi': 'संपादित करें'},
 {'en': '_ Bookmarks', 'hi': 'पुस्तक-चिह्न संपादित करें (_ E)... '},
 {'en': '_ View', 'hi': 'दृश्य _ (V) '},
 {'en': '_ Help', 'hi': 'मदद'},
 {'en': 'Full name', 'hi': 'पूरा नाम'},
 {'en': 'Key binding', 'hi': 'कुंजी बंधन'},
 {'en': 'Content type', 'hi': 'विषय प्रकार'},
 {'en': 'Give your application an accessibility workout',
  'hi': 'अपने अनुप्रयोग को पहुंचनीयता व्यायाम का लाभ दें'},
 {'en': 'Accerciser Accessibility Explorer',
  'hi': 'एक्सेर्साइसर पहुंचनीयता अन्वेषक'},
 {'en': 'The default plugin layout for the bottom panel',
  'hi': 'निचले पटल के लिए डिफोल्ट प्लग-इन खाका'},
 {'en': 'The default plugin layout for the top panel',
  'hi': 'ऊपरी पटल के लिए डिफोल्ट प्लग-इन खाका'},
 {'en': 'A list of plugins that are disabled by default',
  'hi': 'उन प्लग-इनों की सूची जिन्हें डिफोल्ट रूप से निष्क्रिय किया गया है'},
 {'en': 'Highlight duration', 'hi': 'अवधि को हाइलाइट रकें'},
 {'en': 'The duration of the highlight box when selecting accessible nodes',
  'hi': 'पहुंचनीय आसंधि (नोड) को चुनते समय हाइलाइट बक्से की अवधि'},
 {'en': 'Highlight border color',
  'hi': 'सीमांत (बोर्डर) के रंग को हाइलाइट करें'},
 {'en': 'The color and opacity of the highlight border.',
  'hi': 'हाइलाइट किए गए सीमांत का रंग और अपारदर्शिता। '},
 {'en': 'Highlight fill color', 'hi': 'भराई के रंग को हाइलाइट करें'},
 {'en': 'The color and opacity of the highlight fill.',
  'hi': 'हाइलाइट किया गया भराई का रंग और पारदर्शिता। '},
 {'en': 'API Browser', 'hi': 'एपीआई विचरक'},
 {'en': 'Browse the various methods of the current accessible',
  'hi': 'इस समय जिसे प्राप्त किया गया हो, उसकी विभिन्न विधियों (मेथड) में विचरण करें'},
 {'en': 'Hide private attributes', 'hi': 'निजी गुणों को छिपाएं'},
 {'en': 'Method', 'hi': 'विधि'},
 {'en': 'Property', 'hi': 'गुणधर्म'},
 {'en': 'Value', 'hi': 'मान'},
 {'en': 'IPython Console', 'hi': 'आईपाइथन कन्सोल'},
 {'en': 'Interactive console for manipulating currently selected accessible',
  'hi': 'इस समय चुने गए एक्सेसेबेल से काम लेने के लिए अंतर्क्रियात्मक कन्सोल'},
 {'en': 'Event monitor', 'hi': 'घटना मानिटर'},
 {'en': '_ Monitor Events', 'hi': 'घटनाओं को मानिटर करें (_ M) '},
 {'en': 'C _ lear Selection', 'hi': 'चुनाव को हटाएं (C _) '},
 {'en': 'Everything', 'hi': 'सभी'},
 {'en': 'Selected application', 'hi': 'चुने गए अनुप्रयोग'},
 {'en': 'Selected accessible', 'hi': 'चुने गए एक्सेसेबेल'},
 {'en': 'Source', 'hi': 'स्रोत'},
 {'en': 'Event Monitor', 'hi': 'घटना मानिटर'},
 {'en': 'Shows events as they occur from selected types and sources',
  'hi': 'चुने गए प्रकारों और स्रोतों से घटनाएं जैसे-जैसे घटित होती हैं, उन्हें दर्शाता है'},
 {'en': 'Highlight last event entry',
  'hi': 'अंतिम प्रविष्ट घटना को हाइलाइट करो'},
 {'en': 'Start / stop event recording', 'hi': 'घटना रेकोर्डिंग शुरू करो/रोको'},
 {'en': 'Clear event log', 'hi': 'घटना रोजनामचा मिटाओ'},
 {'en': '(no description)', 'hi': 'कोई विवरण नहीं'},
 {'en': 'Description', 'hi': 'वर्णन'},
 {'en': 'Show', 'hi': 'दिखाएं'},
 {'en': '_ Accessible', 'hi': 'पहुंचनीय'},
 {'en': 'Perform action', 'hi': 'कार्रवाई संपन्न करें'},
 {'en': 'Acti _ on', 'hi': 'कार्रवाई (_ o) '},
 {'en': 'ID', 'hi': 'आईडी'},
 {'en': 'Toolkit', 'hi': 'औजार बक्सा'},
 {'en': 'Version', 'hi': 'संस्करण'},
 {'en': 'Ap _ plication', 'hi': 'अनुप्रयोग'},
 {'en': 'Col _ lection', 'hi': 'संग्रह'},
 {'en': '0, 0', 'hi': '0, 0'},
 {'en': 'Relative position', 'hi': 'सापेक्ष स्थिति'},
 {'en': 'Size', 'hi': 'आकार'},
 {'en': 'WIDGET', 'hi': 'विडजेट'},
 {'en': 'Layer', 'hi': 'स्तर'},
 {'en': 'MDI - Z - order', 'hi': 'एमडीआई-जेड-क्रम'},
 {'en': 'Alpha', 'hi': 'अल्फा'},
 {'en': 'Absolute position', 'hi': 'निरपेक्ष स्थिति'},
 {'en': 'Co _ mponent', 'hi': 'घटक'},
 {'en': 'Des _ ktop', 'hi': 'डेस्कटोप'},
 {'en': 'Locale:', 'hi': 'स्थान-विशिष्टः'},
 {'en': '_ Document', 'hi': 'प्रलेख'},
 {'en': 'Hyperlink', 'hi': 'हाइपरकड़ी'},
 {'en': 'H _ ypertext', 'hi': 'हाइपरपाठ'},
 {'en': 'Position', 'hi': 'स्थिति'},
 {'en': 'Description', 'hi': 'वर्णन'},
 {'en': 'Locale', 'hi': 'स्थान-विशिष्ट'},
 {'en': '_ Image', 'hi': 'छवि (_ I) '},
 {'en': 'Lo _ gin Helper', 'hi': 'प्रवेश सहायक'},
 {'en': 'Select All', 'hi': 'सभी चुनें'},
 {'en': '_ Selection', 'hi': 'चयन (_ S) '},
 {'en': 'St _ reamable Content', 'hi': 'प्रवाहित करनेयोग्य विषयवस्तु'},
 {'en': 'Selected columns', 'hi': 'चुने गए स्तंभ'},
 {'en': 'Selected rows', 'hi': 'चुनी गई पंक्तियां'},
 {'en': 'Columns', 'hi': 'स्तंभ'},
 {'en': 'Rows', 'hi': 'पंक्तियां'},
 {'en': 'Table Information', 'hi': '& lt; bgt; सारणी सूचनाlt;/bgt; '},
 {'en': 'name (x, y)', 'hi': 'नाम (x, y) '},
 {'en': 'Header:', 'hi': 'शीर्षकः'},
 {'en': 'Extents:', 'hi': 'विस्तारः'},
 {'en': 'Row', 'hi': 'पंक्ति'},
 {'en': 'Column', 'hi': 'स्तंभ'},
 {'en': 'Selected Cell', 'hi': '& lt; bgt; चुनी गई कोशिकाlt;/bgt; '},
 {'en': '_ Table', 'hi': 'सारणी (_ T) '},
 {'en': 'Offset', 'hi': 'ओफसेट'},
 {'en': 'Include defaults', 'hi': 'डिफोल्टों को शामिल करें'},
 {'en': 'Te _ xt', 'hi': 'पाठ (_ x) '},
 {'en': 'Current value', 'hi': 'मौजूदा मान'},
 {'en': 'Minimum increment', 'hi': 'न्यूनतम वृद्धि'},
 {'en': 'Maximum value', 'hi': 'अधिकतम मान'},
 {'en': 'Minimum value', 'hi': 'न्यूनतम मान'},
 {'en': 'Val _ ue', 'hi': 'मान'},
 {'en': 'Interface Viewer', 'hi': 'अंतराफलक दर्शक'},
 {'en': 'Allows viewing of various interface properties',
  'hi': 'अंतराफलक के विभिन्न गुणों को देखने देता है'},
 {'en': '(not implemented)', 'hi': '(क्रियान्वित नहीं हुआ है) '},
 {'en': 'Name', 'hi': 'नाम'},
 {'en': 'URI', 'hi': 'यूआरआई'},
 {'en': 'Start', 'hi': 'प्रारंभ'},
 {'en': 'End', 'hi': 'अंत'},
 {'en': 'Too many selectable children', 'hi': 'बहुत अधिक चयनीय शिशु हैं'},
 {'en': 'Quick Select', 'hi': 'तेज चुनाव'},
 {'en': 'Plugin with various methods of selecting accessibles quickly.',
  'hi': 'प्लग-इन जिसमें हैं एक्सेसेबेलों को तेजी से चुनने के लिए कई विधियां'},
 {'en': 'Inspect last focused accessible',
  'hi': 'अंतिम बार फोकस किए गए एक्सेसेबल को जांचें'},
 {'en': 'Inspect accessible under mouse',
  'hi': 'माउस के अधीन जो एक्सेसेबल है, उसे जांचें'},
 {'en': 'Native', 'hi': 'वतनी'},
 {'en': 'Dogtail', 'hi': 'श्वानपुच्छ'},
 {'en': 'LDTP', 'hi': 'एलडीटीपी'},
 {'en': 'Script Type', 'hi': 'लिपि प्रकार'},
 {'en': 'Script Recorder', 'hi': 'लिपि रेकोर्डर'},
 {'en': 'Creates dogtail style scripts',
  'hi': 'श्वानपुच्छ शैली की लिपियां निर्मित करता है'},
 {'en': 'The current script will be lost.',
  'hi': 'वर्तमान लिपि (स्क्रिप्ट) खो जाएगी। '},
 {'en': 'Confirm clear', 'hi': 'मिटाने की पुष्टि करें'},
 {'en': 'Sche _ ma:', 'hi': 'स्कीमाः'},
 {'en': 'V _ alidate', 'hi': 'सत्यापन'},
 {'en': 'Idle', 'hi': 'खाली'},
 {'en': 'No description', 'hi': 'कोई विवरण नहीं'},
 {'en': 'AT - SPI Validator', 'hi': 'एटी-एसपीआई सत्यापक'},
 {'en': 'Validates application accessibility',
  'hi': 'अनुप्रयोग की पहुंचनीयता का सत्यापन करता है'},
 {'en': 'Level', 'hi': 'स्तर'},
 {'en': 'Role', 'hi': 'भूमिका'},
 {'en': 'Saving', 'hi': 'सहेज रहे हैं'},
 {'en': 'Validating', 'hi': 'पुष्टि कर रहे हैं'},
 {'en': 'EXCEPT', 'hi': 'अपवाद'},
 {'en': 'ERROR', 'hi': 'त्रुटि'},
 {'en': 'WARN', 'hi': 'चेतावनी'},
 {'en': 'INFO', 'hi': 'सूचना'},
 {'en': 'DEBUG', 'hi': 'दोषमुक्त करें'},
 {'en': 'Basic', 'hi': 'मूल'},
 {'en': 'Tests fundamental GUI application accessibility',
  'hi': 'मूलभूत जीयूआई अनुप्रयोग पहुंचनीयता का परीक्षण करता है'},
 {'en': 'actionable% s is not focusable or selectable',
  'hi': '% s जिस पर कार्रवाई हो सकती है, वह न तो फोकस करने योग्य है न ही चयनीय'},
 {'en': 'interactive% s is not actionable',
  'hi': 'अंतर्क्रियात्मक% s कार्रवाई करने योग्य नहीं है'},
 {'en': 'more than one focused widget', 'hi': 'एक से अधिक विडजेट फोकस में है'},
 {'en': '% s has no text interface', 'hi': '% s का कोई पाठ अंतराफलक नहीं है'},
 {'en': '% s index in parent does not match child index',
  'hi': 'अभिभावक में% s सूची शिशु सूची सेमेल नहीं खाती'},
 {'en': 'Missing reciprocal for% s relation',
  'hi': '% s संबंध के लिए अन्योन्य गायब है'},
 {'en': '% s missing name or label', 'hi': '% s गायब नाम या सूचक'},
 {'en': 'focusable% s has table interface, no selection interface',
  'hi': 'फोकस योग्य% s में सारणी अंतराफलक है, कोई चयनीय अंतराफलक नहीं हैbutton has focused state without focusable state'},
 {'en': '% s has% s state without% s state',

In [4]:
df = ds['train'].to_pandas()

In [5]:
# df1.to_csv("dataset.csv", index=False)

In [6]:
# import pandas as pd

In [7]:
# df = pd.read_csv("./dataset.csv")

In [8]:
df

                                               translation
0        {'en': 'Give your application an accessibility...
1        {'en': 'Accerciser Accessibility Explorer', 'h...
2        {'en': 'The default plugin layout for the bott...
3        {'en': 'The default plugin layout for the top ...
4        {'en': 'A list of plugins that are disabled by...
...                                                    ...
1659078  {'en': 'The Prime Minister, Shri Narendra Modi...
1659079  {'en': 'In a tweet, the Prime Minister said, c...
1659080  {'en': 'I also congratulate all those who took...
1659081  {'en': 'The NDA family will work together for ...
1659082  {'en': 'I assure all possible support from the...

[1659083 rows x 1 columns]

In [9]:
df[:2]

                                         translation
0  {'en': 'Give your application an accessibility...
1  {'en': 'Accerciser Accessibility Explorer', 'h...

In [10]:
df['english'] = df['translation'].apply(lambda x: x['en'])
df['hindi'] = df['translation'].apply(lambda x: x['hi'])

df = df[['english', 'hindi']]

In [11]:
df

,english,hindi
0,Give your application an accessibility workout,अपने अनुप्रयोग को पहुंचनीयता व्यायाम का लाभ दें
1,Accerciser Accessibility Explorer,एक्सेर्साइसर पहुंचनीयता अन्वेषक
2,The default plugin layout for the bottom panel,निचले पटल के लिए डिफोल्ट प्लग-इन खाका
3,The default plugin layout for the top panel,ऊपरी पटल के लिए डिफोल्ट प्लग-इन खाका
4,A list of plugins that are disabled by default,उन प्लग-इनों की सूची जिन्हें डिफोल्ट रूप से नि...
...,...,...
1659078,"The Prime Minister, Shri Narendra Modi has con...",प्रधानमंत्री श्री नरेन्द्र मोदी ने बिहार के मु...
1659079,"In a tweet, the Prime Minister said, congratul...","एक ट्वीट में प्रधानमंत्री ने कहा, बिहार के मुख..."
1659080,I also congratulate all those who took oath as...,"मैं उन सभी को भी बधाई देता हूं, जिन्होंने बिहा..."
1659081,The NDA family will work together for the prog...,एनडीए परिवार बिहार की प्रगति के लिए साथ मिलकर ...
1659082,I assure all possible support from the Centre ...,बिहार के कल्याण के लिए केंद्र की ओर से हरसंभव ...

In [12]:
df.isnull().sum()

english    0
hindi      0
dtype: int64

In [13]:
df.duplicated().sum()

np.int64(219386)

In [14]:
import re
import unicodedata

In [15]:
def process_text(text , lang):
    """ docstring """
    text = str(text)
    
    if lang == 'en':
        text = text.lower()
     
    # normalize unicode (NFKC = compatibility and Composition)
    text = unicodedata.normalize('NFKC',text) 
    
    # remove spaces
    text = re.sub(r"\s+", " ", text)
    
    # Remove weird control characters
    text = re.sub(r"[\u0000-\u001F\u007F-\u009F]", "", text)
    
    
    return text.strip()

In [16]:
df['english'] = df['english'].apply(lambda x:process_text(x,'en'))
df['hindi'] = df['hindi'].apply(lambda x:process_text(x,'hi'))

C:\Users\Naman Rajput\AppData\Local\Temp\ipykernel_13384\168137774.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['english'] = df['english'].apply(lambda x:process_text(x,'en'))
C:\Users\Naman Rajput\AppData\Local\Temp\ipykernel_13384\168137774.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['hindi'] = df['hindi'].apply(lambda x:process_text(x,'hi'))

In [17]:
df["english"].to_csv("data/train_en.txt", index=False, header=False)
df["hindi"].to_csv("data/train_hi.txt", index=False, header=False)

#SentencePiece

In [ ]:
import sentencepiece as spm

spm.SentencePieceTrainer.train(
    input="data/train_en.txt,data/train_hi.txt",
    model_prefix="bpe",
    vocab_size=28000,
    character_coverage=0.9995,
    model_type="bpe",
    pad_id=0,
    unk_id=1,
    bos_id=2,
    eos_id=3
)

In [19]:
import sentencepiece as spm
sp = spm.SentencePieceProcessor()
sp.load('bpe.model')

def encode_text(text):
    """  docstring """
    return [2] + sp.encode(text,out_type = int) + [3]

df['en_ids'] = df['english'].apply(encode_text)
df['hi_ids'] = df['hindi'].apply(encode_text)

In [20]:
df

,english,hindi,en_ids,hi_ids
0,give your application an accessibility workout,अपने अनुप्रयोग को पहुंचनीयता व्यायाम का लाभ दें,"[2, 1607, 424, 3294, 177, 24915, 786, 559, 3]","[2, 334, 5520, 82, 2786, 24029, 20682, 91, 194..."
1,accerciser accessibility explorer,एक्सेर्साइसर पहुंचनीयता अन्वेषक,"[2, 693, 5802, 23428, 24915, 18581, 27845, 3]","[2, 10632, 195, 65, 256, 886, 27846, 2786, 240..."
2,the default plugin layout for the bottom panel,निचले पटल के लिए डिफोल्ट प्लग-इन खाका,"[2, 11, 4543, 5818, 12809, 117, 11, 10316, 114...","[2, 14047, 16938, 32, 162, 24082, 21651, 6152,..."
3,the default plugin layout for the top panel,ऊपरी पटल के लिए डिफोल्ट प्लग-इन खाका,"[2, 11, 4543, 5818, 12809, 117, 11, 3486, 1142...","[2, 10025, 16938, 32, 162, 24082, 21651, 6152,..."
4,a list of plugins that are disabled by default,उन प्लग-इनों की सूची जिन्हें डिफोल्ट रूप से नि...,"[2, 6, 1454, 36, 14007, 166, 222, 12021, 260, ...","[2, 183, 6152, 27904, 27905, 499, 70, 1906, 31..."
...,...,...,...,...
1659078,"the prime minister, shri narendra modi has con...",प्रधानमंत्री श्री नरेन्द्र मोदी ने बिहार के मु...,"[2, 11, 3369, 1870, 27876, 2130, 12012, 10584,...","[2, 3668, 1317, 16928, 9982, 209, 8782, 32, 17..."
1659079,"in a tweet, the prime minister said, congratul...","एक ट्वीट में प्रधानमंत्री ने कहा, बिहार के मुख...","[2, 42, 6, 5, 626, 149, 27876, 11, 3369, 1870,...","[2, 154, 475, 4602, 27894, 63, 3668, 209, 563,..."
1659080,i also congratulate all those who took oath as...,"मैं उन सभी को भी बधाई देता हूं, जिन्होंने बिहा...","[2, 352, 686, 14775, 219, 586, 295, 3420, 9023...","[2, 604, 183, 895, 82, 205, 5005, 1495, 1748, ..."
1659081,the nda family will work together for the prog...,एनडीए परिवार बिहार की प्रगति के लिए साथ मिलकर ...,"[2, 11, 18273, 27838, 2719, 286, 786, 3129, 11...","[2, 3174, 15839, 3215, 8782, 70, 3779, 32, 162..."
1659082,i assure all possible support from the centre ...,बिहार के कल्याण के लिए केंद्र की ओर से हरसंभव ...,"[2, 352, 25610, 219, 3693, 1982, 285, 11, 4153...","[2, 8782, 32, 6615, 32, 162, 2552, 70, 866, 85..."

# Dataset class

In [21]:
import torch

In [22]:
from torch.utils.data import Dataset

class CustomDataset(Dataset):
    """ docstring """
    def __init__(self,df):
        self.source = df['en_ids'].to_list() # explain why to_list() is used
        self.target = df['hi_ids'].to_list()
     
    def __len__(self):
        return len(self.source)  
    
    def __getitem__(self, index):
        return (
            torch.tensor(self.source[index]),
            torch.tensor(self.target[index])
            )

In [23]:
train_dataset = CustomDataset(df)

In [24]:
type(train_dataset)

__main__.CustomDataset

### Collate function for padding

In [25]:
import torch.nn.utils.rnn as rnn

def collate_fn(batch):
    source_batch, target_batch = zip(*batch)
    
    source_batch = rnn.pad_sequence(source_batch, batch_first= True, padding_value=0)
    target_batch = rnn.pad_sequence(target_batch, batch_first= True, padding_value=0)
    
    return source_batch,target_batch

## Small Training Dataset

In [26]:
df_small = df.sample(n=200000, random_state=42).reset_index(drop=True)

In [27]:
len(df_small)

200000

In [28]:
small_train_dataset = CustomDataset(df_small)

## Validation Dataset

In [29]:
from torch.utils.data import DataLoader
val_df = ds['validation'].to_pandas()
val_df['english'] = val_df['translation'].apply(lambda x: x['en'])
val_df['hindi']   = val_df['translation'].apply(lambda x: x['hi'])
val_df = val_df[['english', 'hindi']]

val_df['english'] = val_df['english'].apply(lambda x: process_text(x, 'en'))
val_df['hindi']   = val_df['hindi'].apply(lambda x: process_text(x, 'hi'))

val_df['en_ids'] = val_df['english'].apply(encode_text)
val_df['hi_ids'] = val_df['hindi'].apply(encode_text)

val_dataset = CustomDataset(val_df)
# val_dataLoader = DataLoader(
#     val_dataset,
#     batch_size=32,
#     shuffle=False,
#     collate_fn=collate_fn
#    )

print(f"Validation samples: {len(val_dataset)}")

Validation samples: 520

## Test Dataset

In [30]:
test_df = ds['test'].to_pandas()
test_df['english'] = test_df['translation'].apply(lambda x: x['en'])
test_df['hindi']   = test_df['translation'].apply(lambda x: x['hi'])
test_df = test_df[['english', 'hindi']]

test_df['english'] = test_df['english'].apply(lambda x: process_text(x, 'en'))
test_df['hindi']   = test_df['hindi'].apply(lambda x: process_text(x, 'hi'))

test_df['en_ids'] = test_df['english'].apply(encode_text)
test_df['hi_ids'] = test_df['hindi'].apply(encode_text)

test_dataset    = CustomDataset(test_df)
# test_dataLoader = DataLoader(test_dataset, batch_size=32, shuffle=False, collate_fn=collate_fn)

print(f"Test samples: {len(test_dataset)}")

Test samples: 2507

## DataLoader

In [31]:
from torch.utils.data import DataLoader

small_train_dataLoader = DataLoader(
    small_train_dataset,
    batch_size = 8,
    shuffle=True,
    collate_fn=collate_fn
    # num_workers=4,
    # pin_memory=True,
    # persistent_workers=True
)
train_dataLoader = DataLoader(
    train_dataset,
    batch_size = 8,
    shuffle=True,
    collate_fn=collate_fn
)
val_dataLoader = DataLoader(
    val_dataset,
    batch_size = 8,
    shuffle=True,
    collate_fn=collate_fn
    # num_workers=4,
    # pin_memory=True,
    # persistent_workers=True
)

## Tranformer Model

In [ ]:
import torch.nn as nn

class Custom_Transformer(nn.Module):
    
    def __init__(self, vocab_size, d_model, nhead, num_layers):
         super().__init__()
         
         self.embedding = nn.Embedding(vocab_size,d_model)
         self.positional_encodings = nn.Parameter(torch.randn(5000,d_model))
         
         self.transformer = nn.Transformer(
             d_model=d_model,
             nhead=nhead,
             num_decoder_layers=num_layers,
             num_encoder_layers=num_layers,
             batch_first=True
         )   
         self.fully_connected = nn.Linear(d_model,vocab_size)
    
    def forward(self, source, target):
        
        source = self.embedding(source)
        target = self.embedding(target)
        
        source = source + self.positional_encodings[:source.size(1)]
        target = target + self.positional_encodings[:target.size(1)]
        
        tgt_seq_len = target.size(1)
        tgt_mask = self.transformer.generate_square_subsequent_mask(tgt_seq_len).to(target.device)
        
        # Pass tgt_mask to the transformer
        output = self.transformer(source, target, tgt_mask=tgt_mask)

        output = self.transformer(source, target)
        return self.fully_connected(output)

In [33]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

cuda

In [34]:
model = Custom_Transformer(vocab_size=28000, d_model=256, nhead=4, num_layers=6).to(device)


loss_fun = nn.CrossEntropyLoss(ignore_index=0)
optimizer = torch.optim.Adam(model.parameters(),lr =3e-4)

In [35]:
def evaluate(model, val_dataLoader, loss_fun, device):
    model.eval()
    total_loss = 0

    with torch.no_grad():
        for source, target in val_dataLoader:
            source = source.to(device)
            target = target.to(device)

            output = model(source, target[:, :-1])

            output = output.reshape(-1, output.shape[-1])
            target = target[:, 1:].reshape(-1)

            loss = loss_fun(output, target)
            total_loss += loss.item()

    return total_loss / len(val_dataLoader)

In [36]:
# best_val_loss = float("inf")

# for epoch in range(10):

#     model.train()
#     total_loss = 0

#     # for source, target in small_train_dataLoader:

#     #     source = source.to(device)
#     #     target = target.to(device)

#     #     optimizer.zero_grad()

#     #     output = model(source, target[:, :-1])

#     #     output = output.reshape(-1, output.shape[-1])
#     #     target_shift = target[:, 1:].reshape(-1)

#     #     loss = loss_fun(output, target_shift)

#     #     loss.backward()

#     #     torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)

#     #     optimizer.step()

#     #     total_loss += loss.item()

#     # train_loss = total_loss / len(samll_train_dataLoader)# change

#     # val_loss = evaluate(model, val_dataLoader, loss_fun, device)

#     # print(f"Epoch {epoch}")
#     # print(f"Train Loss: {train_loss:.4f}")
#     # print(f"Val Loss: {val_loss:.4f}")
#     for i, (source, target) in enumerate(small_train_dataLoader):

#         source = source.to(device)
#         target = target.to(device)

#         optimizer.zero_grad()

#         output = model(source, target[:, :-1])

#         output = output.reshape(-1, output.shape[-1])
#         target_shift = target[:, 1:].reshape(-1)

#         loss = loss_fun(output, target_shift)

#         loss.backward()
#         torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)

#         optimizer.step()

#         total_loss += loss.item()

#         if i % 1000 == 0:
#             print(f"Batch {i}/{len(small_train_dataLoader)} | Loss: {loss.item():.4f}")

#     # Save best model
#     if val_loss < best_val_loss:
#         best_val_loss = val_loss
#         torch.save(model.state_dict(), "best_nmt_transformer.pt")
#         print("Model saved!")

In [37]:
#torch.cuda.get_device_properties(0).total_memory

In [38]:
import torch
torch.cuda.empty_cache()

In [ ]:
for epoch in range(1):

    model.train()
    total_loss = 0

    for i, (source, target) in enumerate(small_train_dataLoader):

        source = source.to(device)
        target = target.to(device)

        optimizer.zero_grad()

        output = model(source, target[:, :-1])

        output = output.reshape(-1, output.shape[-1])
        target_shift = target[:, 1:].reshape(-1)

        loss = loss_fun(output, target_shift)

        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)

        optimizer.step()

        total_loss += loss.item()

        if i % 200 == 0:
            print(f"Batch {i}/{len(small_train_dataLoader)} | Loss {loss.item():.4f}")

    train_loss = total_loss / len(small_train_dataLoader)

    val_loss = evaluate(model, val_dataLoader, loss_fun, device)

    print(f"Epoch {epoch} | Train {train_loss:.4f} | Val {val_loss:.4f}")

Batch 0/25000 | Loss 10.3806
Batch 200/25000 | Loss 7.4909
Batch 400/25000 | Loss 7.7664
Batch 600/25000 | Loss 8.2386
Batch 800/25000 | Loss 7.5211
Batch 1000/25000 | Loss 7.4024
Batch 1200/25000 | Loss 7.4572
Batch 1400/25000 | Loss 7.6068
Batch 1600/25000 | Loss 7.4403
Batch 1800/25000 | Loss 7.7308
Batch 2000/25000 | Loss 6.9774
Batch 2200/25000 | Loss 7.4755
Batch 2400/25000 | Loss 6.6722
Batch 2600/25000 | Loss 7.3457
Batch 2800/25000 | Loss 7.6173
Batch 3000/25000 | Loss 7.0564
Batch 3200/25000 | Loss 7.2501
Batch 3400/25000 | Loss 7.1101
Batch 3600/25000 | Loss 7.3855
Batch 3800/25000 | Loss 7.5785
Batch 4000/25000 | Loss 7.2197
Batch 4200/25000 | Loss 7.5297
Batch 4400/25000 | Loss 7.3290
Batch 4600/25000 | Loss 7.2813
Batch 4800/25000 | Loss 7.5331
Batch 5000/25000 | Loss 7.3298
Batch 5200/25000 | Loss 7.3158
Batch 5400/25000 | Loss 7.5520
Batch 5600/25000 | Loss 7.3920
Batch 5800/25000 | Loss 6.8437
Batch 6000/25000 | Loss 7.5932
Batch 6200/25000 | Loss 7.3589
Batch 6400/25000 | Loss 7.6799
Batch 6600/25000 | Loss 7.2152
Batch 6800/25000 | Loss 7.9939
Batch 7000/25000 | Loss 7.1226
Batch 7200/25000 | Loss 7.1192
Batch 7400/25000 | Loss 7.0988
Batch 7600/25000 | Loss 6.8506
Batch 7800/25000 | Loss 7.6213
Batch 8000/25000 | Loss 7.5410
Batch 8200/25000 | Loss 7.6521
Batch 8400/25000 | Loss 6.9406
Batch 8600/25000 | Loss 7.4129
Batch 8800/25000 | Loss 7.2203
Batch 9000/25000 | Loss 7.6478
Batch 9200/25000 | Loss 7.2259
Batch 9400/25000 | Loss 7.1872
Batch 9600/25000 | Loss 7.4412
Batch 9800/25000 | Loss 7.4611
Batch 10000/25000 | Loss 7.2233
Batch 10200/25000 | Loss 7.2861
Batch 10400/25000 | Loss 7.2268
Batch 10600/25000 | Loss 7.8434
Batch 10800/25000 | Loss 7.2303
Batch 11000/25000 | Loss 7.4299
Batch 11200/25000 | Loss 6.8672
Batch 11400/25000 | Loss 7.4612
Batch 11600/25000 | Loss 7.4114
Batch 11800/25000 | Loss 7.3160
Batch 12000/25000 | Loss 7.1527
Batch 12200/25000 | Loss 7.4279
Batch 12400/25000 | Loss 7.1426
Batch 12600/25000 | Loss 7.0774
Batch 12800/25000 | Loss 6.9125
Batch 13000/25000 | Loss 7.4196
Batch 13200/25000 | Loss 7.1526
Batch 13400/25000 | Loss 7.8879
Batch 13600/25000 | Loss 7.1328
Batch 13800/25000 | Loss 7.6015
Batch 14000/25000 | Loss 7.6908
Batch 14200/25000 | Loss 7.0847
Batch 14400/25000 | Loss 6.9115
Batch 14600/25000 | Loss 7.3194
Batch 14800/25000 | Loss 7.7925
Batch 15000/25000 | Loss 6.9986
Batch 15200/25000 | Loss 7.4614
Batch 15400/25000 | Loss 7.5909
Batch 15600/25000 | Loss 7.2482
Batch 15800/25000 | Loss 7.2917
Batch 16000/25000 | Loss 7.2012
Batch 16200/25000 | Loss 7.6587
Batch 16400/25000 | Loss 7.3980
Batch 16600/25000 | Loss 7.1498
Batch 16800/25000 | Loss 7.5158
Batch 17000/25000 | Loss 7.3332
Batch 17200/25000 | Loss 7.3055
Batch 17400/25000 | Loss 7.3469
Batch 17600/25000 | Loss 7.1374
Batch 17800/25000 | Loss 6.9824
Batch 18000/25000 | Loss 7.0657
Batch 18200/25000 | Loss 7.5006
Batch 18400/25000 | Loss 7.3108
Batch 18600/25000 | Loss 7.3571
Batch 18800/25000 | Loss 6.8906
Batch 19000/25000 | Loss 7.0661
Batch 19200/25000 | Loss 7.3685
Batch 19400/25000 | Loss 7.3898
Batch 19600/25000 | Loss 7.1297
Batch 19800/25000 | Loss 7.1948
Batch 20000/25000 | Loss 7.2982
Batch 20200/25000 | Loss 7.3805
Batch 20400/25000 | Loss 7.0893
Batch 20600/25000 | Loss 7.1610
Batch 20800/25000 | Loss 7.3747
Batch 21000/25000 | Loss 7.2203
Batch 21200/25000 | Loss 7.5734
Batch 21400/25000 | Loss 7.0106
Batch 21600/25000 | Loss 7.5584
Batch 21800/25000 | Loss 7.2753
Batch 22000/25000 | Loss 7.6663
Batch 22200/25000 | Loss 7.8988
Batch 22400/25000 | Loss 7.2495
Batch 22600/25000 | Loss 7.0761
Batch 22800/25000 | Loss 7.2502
Batch 23000/25000 | Loss 6.9564
Batch 23200/25000 | Loss 6.9529
Batch 23400/25000 | Loss 7.0003
Batch 23600/25000 | Loss 7.2731
Batch 23800/25000 | Loss 7.0289
Batch 24000/25000 | Loss 7.4601
Batch 24200/25000 | Loss 7.3630
Batch 24400/25000 | Loss 7.1071
Batch 24600/25000 | Loss 7.4713
Batch 24800/25000 | Loss 7.1615
Epoch 0 | Train 7.3412 | Val 7.4905
Batch 0/25000 | Loss 7.3849
Batch 200/25000 | Loss 7.0751
Batch 400/25000 | Loss 7.2041
Batch 600/25000 | Loss 7.2274
Batch 800/25000 | Loss 7.3730
Batch 1000/25000 | Loss 6.7208
Batch 1200/25000 | Loss 7.1317
Batch 1400/25000 | Loss 7.2856
Batch 1600/25000 | Loss 7.2402
Batch 1800/25000 | Loss 7.2448
Batch 2000/25000 | Loss 7.5863
Batch 2200/25000 | Loss 7.4745
Batch 2400/25000 | Loss 7.5465
Batch 2600/25000 | Loss 7.3214
Batch 2800/25000 | Loss 7.3780
Batch 3000/25000 | Loss 6.9117
Batch 3200/25000 | Loss 7.1617
Batch 3400/25000 | Loss 7.2683
Batch 3600/25000 | Loss 7.7563
Batch 3800/25000 | Loss 7.2815
Batch 4000/25000 | Loss 7.5118
Batch 4200/25000 | Loss 7.2138
Batch 4400/25000 | Loss 7.2300
Batch 4600/25000 | Loss 7.4685
Batch 4800/25000 | Loss 7.2976
Batch 5000/25000 | Loss 7.4703
Batch 5200/25000 | Loss 7.1092
Batch 5400/25000 | Loss 7.0431
Batch 5600/25000 | Loss 8.0753
Batch 5800/25000 | Loss 7.2887
Batch 6000/25000 | Loss 7.2422
Batch 6200/25000 | Loss 7.5943
Batch 6400/25000 | Loss 7.2844
Batch 6600/25000 | Loss 7.2611
Batch 6800/25000 | Loss 7.3952
Batch 7000/25000 | Loss 7.4622
Batch 7200/25000 | Loss 7.3150
Batch 7400/25000 | Loss 7.4282
Batch 7600/25000 | Loss 7.3725
Batch 7800/25000 | Loss 7.1937
Batch 8000/25000 | Loss 7.5407
Batch 8200/25000 | Loss 7.0585
Batch 8400/25000 | Loss 7.4151
Batch 8600/25000 | Loss 7.6107
Batch 8800/25000 | Loss 7.4080
Batch 9000/25000 | Loss 7.2225
Batch 9200/25000 | Loss 6.8565
Batch 9400/25000 | Loss 7.3597
Batch 9600/25000 | Loss 7.5200
Batch 9800/25000 | Loss 7.0526
Batch 10000/25000 | Loss 7.3872
Batch 10200/25000 | Loss 7.1220
Batch 10400/25000 | Loss 7.6763
Batch 10600/25000 | Loss 7.1150
Batch 10800/25000 | Loss 7.4734
Batch 11000/25000 | Loss 7.5231
Batch 11200/25000 | Loss 7.1369
Batch 11400/25000 | Loss 7.3956
Batch 11600/25000 | Loss 6.8178
Batch 11800/25000 | Loss 7.1314
Batch 12000/25000 | Loss 7.7078
Batch 12200/25000 | Loss 7.4340
Batch 12400/25000 | Loss 7.1649
Batch 12600/25000 | Loss 7.4678
Batch 12800/25000 | Loss 7.0237
Batch 13000/25000 | Loss 7.2591
Batch 13200/25000 | Loss 7.4418
Batch 13400/25000 | Loss 7.5778
Batch 13600/25000 | Loss 7.2665
Batch 13800/25000 | Loss 7.9808
Batch 14000/25000 | Loss 7.2548
Batch 14200/25000 | Loss 6.9155
Batch 14400/25000 | Loss 7.1653
Batch 14600/25000 | Loss 7.0747
Batch 14800/25000 | Loss 7.3282
Batch 15000/25000 | Loss 7.8382
Batch 15200/25000 | Loss 7.1695
Batch 15400/25000 | Loss 7.5111
Batch 15600/25000 | Loss 7.3545
Batch 15800/25000 | Loss 7.4927
Batch 16000/25000 | Loss 7.3946
Batch 16200/25000 | Loss 7.4084
Batch 16400/25000 | Loss 7.5848
Batch 16600/25000 | Loss 7.2571
Batch 16800/25000 | Loss 7.3237
Batch 17000/25000 | Loss 7.3094
Batch 17200/25000 | Loss 7.5754
Batch 17400/25000 | Loss 7.1116
Batch 17600/25000 | Loss 7.2254
Batch 17800/25000 | Loss 7.4770
Batch 18000/25000 | Loss 7.0732
Batch 18200/25000 | Loss 7.3301
Batch 18400/25000 | Loss 7.3824
Batch 18600/25000 | Loss 7.1621
Batch 18800/25000 | Loss 7.4476
Batch 19000/25000 | Loss 7.5692
Batch 19200/25000 | Loss 7.3697
Batch 19400/25000 | Loss 7.1686
Batch 19600/25000 | Loss 7.5701
Batch 19800/25000 | Loss 7.4033
Batch 20000/25000 | Loss 7.4066
Batch 20200/25000 | Loss 7.5155
Batch 20400/25000 | Loss 7.7213
Batch 20600/25000 | Loss 7.0233
Batch 20800/25000 | Loss 7.3298
Batch 21000/25000 | Loss 7.1054
Batch 21200/25000 | Loss 7.1794
Batch 21400/25000 | Loss 7.3810
Batch 21600/25000 | Loss 7.0720
Batch 21800/25000 | Loss 7.3046
Batch 22000/25000 | Loss 7.6682
Batch 22200/25000 | Loss 7.5164
Batch 22400/25000 | Loss 7.3327
Batch 22600/25000 | Loss 7.0671
Batch 22800/25000 | Loss 7.3003
Batch 23000/25000 | Loss 7.3185
Batch 23200/25000 | Loss 7.2609
Batch 23400/25000 | Loss 7.1879
Batch 23600/25000 | Loss 7.5793
Batch 23800/25000 | Loss 7.2683
Batch 24000/25000 | Loss 7.6006
Batch 24200/25000 | Loss 7.3442
Batch 24400/25000 | Loss 8.0389
Batch 24600/25000 | Loss 7.4326
Batch 24800/25000 | Loss 7.0541
Epoch 1 | Train 7.3227 | Val 7.4688

In [40]:
torch.save(model.state_dict(), "best_transformer_model.pt")
print("Model saved!")

Model saved!

## inference

In [ ]:
model = Custom_Transformer(
    vocab_size=28000,
    d_model=256,
    nhead=4,
    num_layers=6
).to(device)

model.load_state_dict(torch.load("best_transformer_model.pt"))
model.eval()

In [41]:
def translate_sentence(sentence, model, sp, device, max_len=50):

    model.eval()

    tokens = sp.encode(sentence, out_type=int)

    src = torch.tensor([tokens]).to(device)

    tgt_tokens = [sp.bos_id()]

    for _ in range(max_len):

        tgt_tensor = torch.tensor([tgt_tokens]).to(device)

        with torch.no_grad():
            output = model(src, tgt_tensor)

        next_token = output[0, -1].argmax().item()

        tgt_tokens.append(next_token)

        if next_token == sp.eos_id():
            break

    translation = sp.decode(tgt_tokens[1:-1])

    return translation

In [43]:
translate_sentence("How are you", model, sp, device)

''